### ISSUE TITLE
Question 2: R crashes on running correlation [SOLVED]

### ISSUE THREAD

**Issue by psomdeb25** [STAT540-UBC/Discussion#150] opened 2017-02-28 00:28 UTC
@santina @farnushfarhadi @ppavlidis @singha53 

When I run these commands (independently of each other) my R software crashes every time.

df_meta is a joined data set. 
cor(df_meta)
heatmap.2(cor(df_meta))

Can you suggest me what could be the problem?

Thanks!
Somdeb

**Comment by santina** [comment] 2017-02-28 00:45
It doesn't really make sense to do cov(df_meta) if df_meat is your metadata. It doesn't have any numerical information about your gene expression, only the information about what each sample is about (number of hours, treatment type). 

What do you mean by "df_meta is joined data set"?

**Comment by psomdeb25** [comment] 2017-02-28 00:56
I have fused my data.txt and the meta file into df_meta.

**Comment by santina** [comment] 2017-02-28 01:08
I'm guessing this is for the heatmap problem. You don't need your metadata to find sample-to-sample correlations. Everything is already in the zipped gene data set, in which each column is a sample. 

If you want to know why it crashes, you'd need to describe, or in terms of the code you run, how you join the metadata and the gene data together.

**Comment by psomdeb25** [comment] 2017-02-28 02:16
Following is the code that I am using:

library(dplyr)
library(gplots)
library(RColorBrewer)
library(pheatmap)

setwd("/Users/somdebpaul/GSAT 540/STATS ASSNMNT/assignments/Analysis Assignment")
meta <- read.table("NHBE_design.txt")
df <- read.table("data.txt")



time_meta <- meta$time
time_meta <- gsub("_h", "", time_meta)
meta$time <- as.numeric(time_meta)

df_meta <- cbind(meta, t(df))
df_meta <- df_meta[ order(df_meta$time, df_meta$Treatment), ] 

df_meta[1:3] <- NULL

pheatmap(cor(df_meta, df_meta))

**Comment by dejonggr** [comment] 2017-02-28 03:23
RStudio also crashes when I run the correlation (also with pheatmap). Initially I tested it with the reordered probes, then I tested it using the data.txt as directly read from the table. It takes R about 20 minutes to either crash or respond with an error along the lines of "exceeds available space" or something to that effect.

**Comment by singha53** [comment] 2017-02-28 06:50
@psomdeb25 @dejonggr Are your samples in your rows or columns? cor() computes the correlation between columns. you might be trying to compute the correlation between all your 20K genes (reason for crash).

@psomdeb25 
df_meta <- cbind(meta, t(df))   --> only compute the correlation using the gene expression data cor(df).

**Comment by dejonggr** [comment] 2017-02-28 07:29
I've resolved the issue! There was a problem with the software.

**Comment by psomdeb25** [comment] 2017-02-28 07:32
@singha53  I have resolved the issue too. It was because of the mechanics of the heatmap function

**Comment by gjahesh** [comment] 2017-02-28 16:07
@psomdeb25 @dejonggr  I have the same issue, could you please explain how did you fix it?Just using a diff computer/software?

**Comment by psomdeb25** [comment] 2017-02-28 16:52
@gjahesh Is your genes/probes along the columns and samples along your rows? If that is the case, refer to what @singha53 mentioned in the comments. You can just transpose your matrix and try again.

**Comment by gjahesh** [comment] 2017-02-28 17:23
@psomdeb25 I have done matrix transpose, I also have used diff heatmap functions i.e `heatmap2` and `Heatmap`, same issue with both functions.

**Comment by dejonggr** [comment] 2017-02-28 17:43
That's your problem, since cor() calculates correlation on columns, if you
transpose you're asking R to calculate the correlation 27000^2. Don't
transpose.

**Comment by ppavlidis** [comment] 2017-02-28 18:21
Coming late to this I realize the problem is probably found now. But I want to offer some general debugging advice: break your code down into steps, and test on toy data.

If heatmap.2(cor(mydata)) fails, the point of failure may be ambiguous. If you notice that cor(mydata) fails in isolation, that's the place to look. Stop there. Forget about heatmap.2 until you get cor(mydata) to work.

If I can't get cor(mydata) to work, I would try cor(someToyDataMatrix) to make sure there isn't something really strange going on - if you look at the documentation for cor, you'll see there are examples - do they work? If so, then I know for sure that it's the data input. Something like cor(mydata[1:100,1:10]) can help you see if maybe the size of the data is the problem vs. the data itself. And so on...

There are more advanced debugging methods (like debug()) but 9/10 times steps like the above rapidly lead to identification of the issue, if not the resolution.

@psomdeb25 beyond getting code to run, I also want to make sure there isn't a conceptual issue here. Taking correlations with your meta-data merged with the expression data would have worked if all the metadata are numeric, and you probably wouldn't not have noticed anything was amiss. Did you understand why we don't want you to use the metadata here?

**Comment by psomdeb25** [comment] 2017-02-28 21:20
@ppavlidis I follow the concept of not attaching my meta-data to the gene expression data while performing my heatmap and correlation. Therefore, I have detached my metadata from my gene expression frame after ordering and sorting as asked in the question. Hence, the dataframe that I use in my heatmap(cor()) does not contain the metafile. 

Could that cause a problem in the analysis down the line?

**Comment by ppavlidis** [comment] 2017-02-28 22:57
> Could that cause a problem in the analysis down the line?

I'm not completely sure what you mean by "that". If you mean "keeping the metadata separate" I definitely recommend keeping the two matrices separate; it's very inconvenient to have them together since you often need to handle one or the other (as you have learned). You should be using an eSet object to keep things organized.

@santina @farnushfarhadi We used to use eSets in the seminars, has that content been removed?

But @psomdeb25 let me know if I answered the right question!

**Comment by farnushfarhadi** [comment] 2017-03-01 01:50
@psomdeb25 If I get your question correctly, you don't necessarily want to use your input for `cor` in other lines of your code. You just want to make sure each variable passed to your functions are correctly formatted and have the right information. 

@santina do you know what Paul is referring to? Never seen name of `eSets` before ...

**Comment by ppavlidis** [comment] 2017-03-01 03:10
Seems that the use of eSet has been dropped from the course materials somewhere along the line. It's part of Bioconductor Biobase (so you can do ?Biobase::eSet to read about it; the implementation you would use is ExpressionSet via the constructor described in the docs).

It's just an object that holds the meta-data (they call it phenoData) and data ("assayData") together (as well as the gene annotations, "featureData") in a way that is easy to handle, so you can do subsetting without worrying about the meta-data and data getting scrambled, etc., and many bioconductor packages know about it. Or at least, they used to ...

But it sounds like that wasn't relevant to what @psomdeb25 is asking.

**Comment by santina** [comment] 2017-03-01 06:39
I didn't know what eSets was until Paul explained it. Sounds interesting. Maybe it's still being used in Bioconductor packages as a dependency?

@psomdeb25 
I only know pheatmap but I think other heatmap packages are similar. You only need the data to create correlations as input to your heatmap, and then you use the metadata to determine the ordering and label of the samples (which sample belongs to what groups: control/smoke, time)

**Closed** 2017-03-01 22:08 UTC
