### ISSUE TITLE
Assignment 1 peer evaluation

### ISSUE THREAD

**Issue by dtebaykin** [STAT540-UBC/Discussion#69] opened 2015-03-09 17:21 UTC
Hi,
5 points for our assignment 1 is in the peer review evaluation - have the guidelines been posted somewhere or is it going to be posted at a later date?
Thank you.

**Comment by AlisonMcAfee** [comment] 2015-03-10 20:25
I am wondering the same thing.. I have found the rubric but not any more information.

**Comment by jennybc** [comment] 2015-03-10 20:26
Ack! I promised to open peer review issues for you all last night then forgot. Will see if I can get this rolling right now! @gcohenfr

**Comment by swils6** [comment] 2015-03-10 21:06
For future classes, it would have been helpful to have the rubric when completing the assignment to have an idea exactly what you were looking for.

**Comment by jennybc** [comment] 2015-03-10 22:43
The issues are assigned now. Unless you've shut down all email notifications, I'd expect each student to have received two emails, each alerting them to a peer review assignment.

**Comment by dtebaykin** [comment] 2015-03-10 22:46
I believe each of us has received 4 emails - 2 assignments for us to review and 2 people that were assigned to review our homework. If the reviews were supposed to be anonymous they definitely no longer are.

**Comment by AlisonMcAfee** [comment] 2015-03-10 23:00
I received 6 emails, and personally I don't feel comfortable doing this unless it is anonymous (at least to other students, obviously it should not be anonymous to the instructors)

**Comment by swils6** [comment] 2015-03-10 23:01
I agree, I would feel more comfortable if this was anonymous.
Also, another point is that there are no criteria for biological interpretation. As this was stressed in class and I think is very important to analyzing biological data. I think this should be included.

**Comment by chainikonwar** [comment] 2015-03-10 23:04
I agree. I think "biological interpretation"  of the results is as important as the approach used to solve the problem or the code.Probably, It should have been included in the rubric

**Comment by jennybc** [comment] 2015-03-10 23:08
The four emails described by @dtebaykin actually make sense to me. I'm not too sure why @AlisonMcAfee would have received 6. If you wanted to forward those to me at jenny@stat.ubc.ca, I can try to unravel the cause. Perhaps I should change something or maybe that's what happens when maximal email notifications are switched on.

As for anonymity, we did the same, i.e. non-anonymous peer review, in STAT 545. Students actually submitted a mark privately to another system, but I don't think STAT 540 plans to do so. Maybe some of the STAT 545 alums here can chime in? But I think the peer review worked well. You just get another sympathetic, interested set of eyeballs going over your work. The comments from peers can reveal a lot about which parts of the work are well explained vs. a bit mysterious. It can also be gratifying to learn that your peers learned some coding tricks from you! You will also find cases where you can really help a peer out, by suggesting how to do something that seemed to stump them. Maybe "peer feedback" better captures the spirit of this.

I'll leave it to @gcohenfr to handle your comments re: the rubric. I'm only helping out with the GitHub mechanics of this.

**Comment by jkbooth** [comment] 2015-03-10 23:17
I agree that identified/non-anonymous peer comments worked well in STAT 545. It's not necessary to say anything hurtful or contentious. Knowing the expertise and background of your peers makes their commentary more informative. Plus, that way you can have a conversation about your submission rather than receiving something you can't respond to.

**Comment by rmcclosk** [comment] 2015-03-11 01:08
What are we supposed to do if the student we are assigned to peer review has not posted his or her homework?

**Comment by aliceZhu** [comment] 2015-03-11 01:33
@rmcclosk yes, there are 2 students (you and Daniel  ) assigned to view an auditing student's repo, so there is no hw1 available from that student. That auditing student is assigned to peer review another 2 students' hw1, so I think the quickest solution is to assign that 2 students to you and Daniel, @gcohenfr  Gaby , please let me if it sounds ok, then we can proceed to assign new students to Rosemary and Daniel

**Comment by AlisonMcAfee** [comment] 2015-03-11 21:07
@jennybc, don't worry about the 6 emails; some were duplicates. I still only have two to review.

Cheers

**Comment by rmcclosk** [comment] 2015-03-13 20:37
@aliceZhu @jennybc @gcohenfr Have I been assigned a new student? The deadline is fairly soon and I'd like to get started :smile:

**Comment by aliceZhu** [comment] 2015-03-13 20:46
Hi @rmcclosk , you were assigned to view alander-max and ye-bin(the auditing student), right?  The auditing student was assigned to view mcewen-lisa and yap-shyong-quin. Gaby @gcohenfr , is it fine to assign either mcewen-lisa or yap-shyong-quin to Rosemary?

**Comment by gcohenfr** [comment] 2015-03-14 05:59
Yes, please, re-assign. We got another of this case, which we solved in a similar way.

**Comment by gcohenfr** [comment] 2015-03-14 06:05
I agree with previous comments made about rubric and will take your suggestions to tailor the rubric for STAT540. However, the rubric was suggested only as a guide. You can add/remove points from it as you think it is appropriate for STAT540 and for the homework.

**Comment by gcohenfr** [comment] 2015-03-14 06:13
I agree with @jennybc comments about anonymity. You are not grading your peer so as long as you make constructive comment, you can be transparent. Your review can be rewarding and, at the very worst, it should help your peer to improve. Our hope is that you find the process interesting and you learn how other people code, think, and communicate their work. In addition, as @jkbooth mentioned, you can also respond to your reviewer with further comments, observations and discussion if you want.

**Comment by dchiu911** [comment] 2015-03-14 08:43
Yes the STAT 545 peer reviews worked well! An advantage of having transparency is it helps the reviewer be more conscientious while writing the feedback. Also, the focus is on constructive criticism and evaluation, useful skills to have in the real world, where full anonymity may or may not be guaranteed. It also feels nice when someone appreciates your work and you know who they are!

**Comment by gcohenfr** [comment] 2015-03-16 18:42
@rmcclosk, I've assigned you yap-shyong-quin's hw01 to review. If you don't get an email from the issue I've opened, visit zz_yap-shyong-quin_STAT540_2015 repository and find the new issue there to place your review.

**Closed** 2016-01-10 20:45 UTC
