### ISSUE TITLE
Group project: initial information

### ISSUE THREAD

**Issue by santina** [STAT540-UBC/Discussion#109] opened 2016-01-27 17:24 UTC
Hello teams! Please write a paragraph about your project, and also include the list of your team members (+their Github IDs) the name of your team so we can create group project repo for you all. 

Just one post per group. Thanks!  Please do this by this Friday (January 29) :smile_cat:  
If you already wrote all that information (project description, team name, etc) in your team formation issue, then simply copy paste or link your post to that issue.

Tagging for attention: @saramostafavi @marjanfarahbod @ppavlidis 

source: [Initial project proposal](http://stat540-ubc.github.io/subpages/assignments.html#initial-deliverables)

**Comment by eclaks** [comment] 2016-01-27 19:28
Group issue: https://github.com/STAT540-UBC/Discussion/issues/101
Group name: treed
GitHub ID            | Name (Department)
----------------------|---------------------------------------------------
@RashedHUBC           |Rashed Hoque (Statistics)
@emminic93            |Emma Titmuss (Genome Science and Tech)
@eclaks               |Emma Laks (Genome Science and Tech)
@hui-tony-zk          |Tony Hui (Genome Science and Tech - Bioinformatics)
@david-rattray        |David Rattray (Biochemistry)

Abstract: 
Male rats have lower DNA (cytosine-5)-methyltransferase 3A (DNMT3a) activity and DNA methylation than females. Nugent et al demonstrated using DNMT inhibitors or conditional knockouts that female rats display masculinized behavior. We will analyze their RNA-seq data from male and female rats with and without DNMT inhibitor treatment to relate the involvement of gene expression to differentially methylated regions found in females with and without estradiol therapy and male rats using their Whole Genome Bisulfite Sequencing (WGBS) data. We will conduct some exploratory analysis on both data through appropriate graphical visualization. After that to compare the different gene expressions and epigenetic characteristics we will use t-tests for two-groups (explicitly male and female) and ANOVA or analysis of variance (for more than two groups). Also if data permits some linear models will be checked for fitting to express the relationship in a formal way. 

@santina 
@marjanfarahbod 
@saramostafavi

**Comment by fergusonandrew** [comment] 2016-01-27 19:46
## METAgenomic Viticulture and Enology Group | (META-VEG)

#### Initial project information

##### Our research team:

Jay Martiniuk | LFS WRC* (Food Science) | @jmartiniuk
Nicolas Dimopoulos | LFS WRC* (Plant Biology) | @ndimopoulos
Andrew Ferguson | LFS WRC* (Food Science) | @fergusonandrew

*Faculty of Land and Food Systems, Wine Research Centre

##### Our research project:

We have an RNAseq dataset generated from grape (*Vitis vinifera*) berry samples taken a multiple stages of development, and also indexed for berry firmness (a secondary indicator of ripening). The datasets were originally compiled to look at grape gene expression throughout development, but they also contain as the berry surfaces were not sterilized, the dataset also contains information about the microbial communities living on the surface of the berries. These fungi and bacteria can have both beneficial and detrimental impacts on grape and wine quality (e.g. presence of pathogens, spoilage or helpful fermenting yeast).

The goal of our project is to analyze the microbial population on the surface of grape berries and correlate this data with berry development and berry firmness.  We would like to further analyze the direct correlation between the expression of particular genes related to cell wall degradation (microbes), sugar consumption (microbes), and plant defines (grapes).  We hope to be able to better understand **genetic interactions between grape berries and their microflora**.

@santina 
@marjanfarahbod 
@saramostafavi
@ppavlidis

**Comment by lulock** [comment] 2016-01-27 20:19
### Group Name:
![image](https://cloud.githubusercontent.com/assets/8599836/12626856/a74ca606-c4ef-11e5-9787-5f792bf18954.png)
___
### Group Members:
**G**enevieve Rocheleau | Experimental Medicine | @genrocheleau
**L**ouie Dinh | Computer Science | @louiedinh
**L**eila Methnani | Computer Science | @lulock
**A**ngela Mo | Pathology and Laboratory Medicine | @angelamo
**D**erek Cho | Statistics | @derekcho

### Our project:
We will look at RNA micro-array gene expression data in monocytes collected from HIV/HCV co-infected population, as well as HCV mono-infected and a healthy comparison group. the participants in this study were actively taking antiretroviral drugs to suppress their HIV viral loads. Our goal is to identify cellular pathways that are differentially expressed in the retrovirus infected populations. This could be beneficial in identifying potential pathways for therapeutic targets. We would also be able to analyze the cellular difference pertaining to HCV, by comparing the HIV/HCV co-infected and HCV mono-infected group. It is important to elucidate the role of HCV in HIV/HCV co-infection because in BC, where the majority of HIV infected people are intravenous drug users, roughly 80% of HIV infected intravenous drug users have HCV. 

@santina 
@marjanfarahbod 
@saramostafavi

**Comment by shamsbhuiyan** [comment] 2016-01-29 16:47
Our team Members:

Jasleen Grewal | Bioinformatics | @jasgrewal
Wendy Zhang | Experimental Medicine |@w-zhang
Shamsuddin A. Bhuiyan | Bioinformatics | @shamsbhuiyan
Phillip Richmond | Bioinformatics | @Phillip-a-Richmond
Rachelle Farkas | Bioinformatics | @rafarkas

### Team JaWSPR: Expression Analysis of an Alcohol Tolerance Mouse Model

 **Ja**sleen Grewal, **W**endy Zhang, **S**hams Bhuiyan, **P**hillip Richmond, **R**achelle Farkas
January 29th, 2016

In 1981, McClearn greatly impacted the alcohol sensitivity field when he introduced the world to the Inbred Long Sleep (ILS) and Inbred Short Sleep (ISS) mice [MCCLEARN 1981 REF]. The strains were selected for and named by their variable response to a high dose of alcohol, which is measured by a phenomenon known as the Loss of Righting Reflex (LORR).  After roughly 30 generations of selection for this trait, the resultant lines were inbred through brother sister mating to produce an isogenic line. Initial hypotheses regarding metabolic rate were investigated, but were disproven and the sensitivity was linked to differences in the brain [Kakihana 1966 REF].  The ILS and ISS mice were also crossed and inbred to produce the recombinant inbred (RI) panel named LXS—which spans a sleep time spectrum—allowing for mapping of traits in a quantitative trait loci (QTL) manner [Williams 2004 REF].  Presently, we have the unprecedented ability to investigate the gene expression profiles of these mice using RNA-sequencing, which is exactly what Richard Radcliffe at the University of Colorado School of Pharmacology decided to pursue.  Dr. Radcliffe has been studying these mice for the past 15 years, and designed an experiment that includes RNA-sequencing of the brains of the ILS, ISS, and 40 individual LXS strains under both saline and ethanol treatment.  The data generated in the course of this experiment has resulted in a total of 252 RNA-seq libraries from mice whole-brain samples, covering the 2 conditions (saline control and ethanol treatment), with 3 biological replicates for each condition, and a few sets of technical replicates. A bioinformatics based analysis of this dataset will entail identification of significant expression differences between the ILS and ISS cohorts, using the saline treated strains as respective controls for normalizing against batch and technical effects. Additionally, we will look for gene expression trends and patterns in the LXS RI panel.  Since the panel represents a spectrum of phenotypes, we may also expect a subset of genes to be expressed in a spectral manner—modulating across genotypes.  The main intent of this analysis is to identify expression signatures that distinguish the ethanol sensitivity phenotype. The resultant signatures that we observe can then be used by Dr. Radcliffe’s lab in downstream expression-QTL (eQTL) analyses, linking genotypes to expression patterns in an effort to further decode the molecular mechanisms behind sensitivity to alcohol. 


_References_
Kakihana R, Brown DR, McClearn GE, Tabershaw IR. Brain sensitivity to alcohol in inbred mouse strains. Science 154, 1574-1575 (1966) 

McClearn GE. Genetic differences in the effect of alcohol upon behaviour of mice. In Proceedings of the third international conference on alcohol and road traffic, J. Havard, ed. London: British Medical Association, pp 153-155 (1962) 

McClearn GE, Kakihana R. Selective breeding for ethanol sensitivity: Short-Sleep and Long-Sleep mice. In Development of Animal Models as Pharmacogenetic Tools, M.G. E., R.A. Deitrich, V.G. Erwin, eds. Rockville, MD: National Institute on Alcohol Abuse and Alcoholism, pp 147-159 (1981) 

Williams RW, Bennett B, Lu L, Gu J, DeFries JC, Carosone-Link PJ, Rikke BA, Belknap JK, Johnson TE. Genetic structure of the LXS panel of recombinant inbred mouse strains: a powerful resource for complex trait analysis. Mamm Genome 15, 637-647 (2004)

**Comment by gdelgobbo** [comment] 2016-01-29 21:36
## IUGRoup: DNA methylation analysis in intrauterine growth restriction-associated placentas

James Melanson | Experimental Medicine | @jamesmelanson
Kate Watt | Reproductive and Developmental Sciences | @hannibelle
Giulia Del Gobbo | Medical Genetics | @gdelgobbo
Luke Gooding | Reproductive and Developmental Sciences | @ldgooding
Samuel Schafer | Reproductive and Developmental Sciences | @schafers

***

#### Project Proposal:

Intrauterine growth restriction (IUGR) is a pregnancy complication characterized by impaired fetal growth, occuring in approximately 5-7% of the population. This delayed growth *in utero* puts the baby at increased risk for perinatal mortality, a number of perinatal complications, and health problems in later life. A main cause of IUGR is placental insufficiency. Due to a lack of optimal growth and invasion of the placenta into maternal tissue, it is unable to extract and deliver adequate nutrients and oxygen to the fetus, resulting in slowed fetal growth. 

It has been previously demonstrated that placentas from IUGR pregnancies exhibit different DNA methylation (DNAm) patterns compared to those from healthy pregnancies (Banister et al. 2011). This altered DNAm could be a simple biomarker for IUGR, or could perhaps be an underlying cause for the disease itself, as DNAm, especially at promoter sequences, can be associated with gene expression (Tate and Bird 2003). The goal of our research project is to investigate DNAm in placentas associated with IUGR compared to controls to identify both global and site-specific differences between these two groups. We will be analyzing placental DNAm data acquired via the Illumina Infinium HumanMethylation450 Beadchip from 12 IUGR-complicated pregnancies and 20 healthy control pregnancies. We will determine whether different genomic regions (ie gene promoters, gene bodies etc) display significantly altered DNAm in IUGR-associated placentas. We will also investigate whether there are specific sites that are significantly differentially methylated between IUGR and control placentas, and determine whether these sites could be functionally related to the placental insufficiency/IUGR phenotype. Ultimately, we hope to replicate previous findings of a differential methylation pattern associated with IUGR placentas, and gain insight into certain biological pathways that could be affected by altered DNAm in the placenta.


**References:**

Banister CE, Koestler DC, Maccani MA, Padbury JF, Houseman EA & Marsit CJ (2011). Infant growth restriction is associated with distinct patterns of DNA methylation in human placentas. *Epigenetics* 6:920-927.

Tate PH & Bird AP (1993). Effects of DNA methylation on DNA-binding proteins and gene expression. *Current Opinion in Genetics & Development* 3:226-231.

**Comment by hannibelle** [comment] 2016-01-29 21:39
That looks awesome, Giulia!! Thanks for taking the helm on that, you're amazing.

**Comment by halldorbjarni** [comment] 2016-01-30 01:16
## Mass spectrometry-based metabolomics for discovery of novel inborn errors of metabolism causing hyperphenylalaninemia.

###  Group Name: FISCH

**Team members:**
Halldor Bjarni Thorhallsson | Computer Science | @halldorbjarni
Chris May | Interdisciplinary Oncology | @cgmay
Ian Garber | Experimental Medicine | @igarber
Samuel Hinshaw | Bioinformatics | @samhinshaw
Farnush Farhadi | Bioinformatics | @farnushfarhadi

---

## Project Proposal

**Data characteristics:**
High resolution mass spectrometry data obtained by liquid chromatography-quadrupole-time of flight (LC-QTOF) analysis of human blood (plasma). This measures the concentration of all small molecule (<1 kDa) metabolites present. Data have been pre-processed and aligned in the time domain to allow comparison between samples. There are approximately 5000 chemical “features” seen, consisting of unique combination of mass-to-charge ratio and chromatographic retention time. Signal intensity for each “feature” is recorded for each biological sample.

There are 16 biological samples: 6 patients found to have high plasma phenylalanine concentration of unknown cause, and 10 healthy controls with approximately the same age and sex distribution. The common genetic causes of hyperphenylalaninemia, including phenylketonuria (PKU), have been ruled out.

**Proposed analysis:**
Exploratory analysis will include the following:

1) Each “feature” belongs to a single chemical compound, but due to ion fragmentation, a single chemical may yield multiple features. This leads to redundancy in the data set. Data reduction, by grouping coincident signals that correlate with each other, should facilitate downstream analysis, particularly in the final step of assigning the identity of chemical compounds.

2) The primary biological question is to identify metabolites that are significantly increased or decreased in these patients compared to controls. By mapping these to metabolic pathways, we aim to:
   a) Identify novel enzyme defects causing high phenylalanine.
   b) Identify downstream metabolites and pathways affected by increased phenylalanine.


@santina 
@marjanfarahbod 
@saramostafavi

**Comment by joeho604** [comment] 2016-01-30 02:41
# The Human Microbiome Project

## Group Name: **GutCHECK**

### ## Our team members:

Dan Seale | GSAT | @danseale
Kevin Ao | GSAT | @kao7
Amalia Rose | Biochemistry |@amaliar
Joe Ho | Microbiology | @joeho604
_______________________________________________________________________________

##** Project Proposal**
The recent studies of the human microbiome have generated vast datasets of metagenomic sequences. These datasets include the study of human-associated microbial communities that exist across different habitats of the human body, in healthy and diseased populations. With compiled datasets of recent gut microbiome projects, we are interested in studying the metagenome-wide associations of gut microbial DNA and disease outcomes of patients diagnosed with type 2 diabetes (T2D) and inflammatory bowel disease (IBD).

Our goals for this project are to analyze the microbial abundance, diversity and metabolic functions of microbial communities that exist across ethnicities and cultures (US (subdivided into caucasian and asian populations), European, and Chinese) and across diseased populations. Using 16S rRNA sequence analysis, we can decipher the abundance and diversity of microbial clades in the metagenomic data. In association with this analysis, we will predict the open reading frames (ORFs) and genes covered by microbial species represented in individuals participating in these datasets.  Through the genes predicted, we will map the gene abundances or metabolic pathways associated with the different health conditions and racial and geographical populations. For example, in T2D individuals, we have interest to predict and identify polysaccharide utilization loci using CAZy databases of catalytic and carbohydrate binding enzymes that are involved in modification of sugar molecules. Studying the abundance and distribution of these enzymes across microbial communities will enable us to understand their function in disrupting glucose homeostasis. Additional analyses may include genomic island identification or counts to distinguish genes that have been horizontally transferred and over-represented within microbial communities. 

Overall, the outcome of the project will be the correlation of microbial composition and metabolic pathways with disease conditions, ethnicity and geographical location.  

**References:**

1.	Qin, J. et al. A metagenome-wide association study of gut microbiota in type 2 diabetes. Nature 490, 55–60 (2012).
2.	Qin, J. et al. A human gut microbial gene catalogue established by metagenomic sequencing: Commentary. Nature 11, 28 (2010).
3.	Human, T. & Project, M. A framework for human microbiome research. Nature 486, 215–21 (2012).
4.	Human Microbiome Project Consortium, T. Structure, function and diversity of the healthy human microbiome. Nature 486, 207–214 (2012).




@santina
@marjanfarahbod
@saramostafavi
@pp

**Comment by Irrationone** [comment] 2016-01-30 04:47
**Characterizing the effect of the immune microenvironment on tumour evolution in high-grade serous ovarian cancer**

**Group name: PHASAX**

**Background**
High-grade serous ovarian cancer (HGSC) is a challenging disease characterized by poor survival and relapse. The current standard of treatment, platinum-based chemotherapy, is initially effective at treating the disease. However, the majority of patients develop and eventually succumb to treatment resistant disease. It is now believed that intratumoural heterogeneity -- the phenomenon that tumours are composed of multiple, genotypically distinct, malignant cell populations -- drives tumour evolution and is responsible for treatment resistance in many cancers. Our groups (Shah & Nelson labs) have recently observed remarkable survival benefit associated with the presence of tumour-infiltrating lymphocytes (TILs), suggesting a role for TILs in contending with intratumoural heterogeneity. In collaboration with the Holt lab, we have generated a rich set of immune cell sequencing data -- T-cell and B-cell receptor sequencing (TCR/BCR-seq) -- from spatially sampled sites in HGSC patients. This type of data allows for unparalleled resolution in characterizing immune cell populations and their interaction with malignant clonal populations, giving us the ability to study the links between intratumoral heterogeneity and immune responses.

**Rationale**
We believe that diversity in TCR/BCR-seq profiles will be associated with intratumoural heterogeneity -- specifically, that clonally heterogeneous tumours will recruit diverse immune responses. 

**Project Outline**
Data generated from the Shah, Nelson & Holt labs has already analyzed other types of data (immunohistochemistry, whole-genome sequencing, amplicon deep sequencing) to address this hypothesis. Our STAT 540 group’s focus will be on analyzing TCR-seq and BCR-seq data, associating our findings with this dataset to other available datasets. If necessary, additional datatypes from our patient samples (DNA methylation and gene expression) are available to characterize how intratumoral heterogeneity coalesces with multiple factors to contribute to lethality. Multiple peritoneal tumor samples from varying immune microenvironments will provide snapshots of the relationship between the TILs and malignant clonal populations.

**Participants & roles**
**Enrolled students: **
@pjobin10
Biological background for the project -- interpreting & teaching other project members about the nature of T-cell receptor sequencing data, and identifying the potential impacts of confounding factors such as anatomic site. 
@IreneDing
Statistical expertise for the project -- developing methods to assess diversity in T-cell and B-cell populations. 
@AnnieXuanLi
Statistical expertise for the project -- improving and developing methods to associate diversity in T-cell and B-cell populations with computed intratumoural heterogeneity measures. 
@Irrationone
Bioinformatics expertise & expertise with the dataset -- Provider and experienced with manipulating and analyzing data of this nature. Will be analyzing the differences between T-cell receptor/B-cell receptors across molecular (gene expression) subtypes. 

**Auditors:**

@hochoy  Rstudio-script writing, Looking at tumour heterotypes and how they are related. The (putative) relationship can be used to classify the tumour profiles into smaller groups.  
E.g. We can classify: (Early stage, Mid stage, Late stage), (Apical, basal, lateral position), (Invasive-type, Less-invasive-type), (fast growth, quiescent)

@shumin11 Practise R studio of gene expression analysis for T-cell receptor / B-cell receptors (specifically for the immune markers, what are the differences among the 8 patients). Help with organizing the poster and printing it.  


@santina
@marjanfarahbod
@saramostafavi
@ppavlidis

**Comment by marjanfarahbod** [comment] 2016-02-02 20:32
Dear all! 

With your project groups formed and confirmed, we have assigned each team an Instructor and a TA and therefore the initial steps for group project formations is done... you are all set! 

Have fun doing these amazing projects and best of luck!

**Closed** 2016-11-29 04:23 UTC
